AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'gemfiles/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/MutableConstant:
  Exclude:
    - 'lib/country_select/defaults.rb'
    - 'lib/country_select/formats.rb'

Style/MethodCallWithoutArgsParentheses:
  Exclude:
    - 'lib/country_select/tag_helper.rb'

