name: Tests

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, '3.0', 3.1, 3.2]
        gemfile: [5.2, '6.0', 6.1, '7.0']
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/actionpack-${{ matrix.gemfile }}.gemfile
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
